// <auto-generated />
using CurrencyRepository.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CurrencyRepository.Migrations
{
    [DbContext(typeof(CurrencyDBContext))]
    [Migration("20241214072853_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CurrencyRepository.Models.CurrencyModel", b =>
                {
                    b.Property<string>("DateConversion")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("ConversionValue")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("DateConversion");

                    b.ToTable("Currencies");
                });
#pragma warning restore 612, 618
        }
    }
}
